movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    path(route="", view=views.index, name="index"),
    path(route="<int:movie_id>", view=views.detail, name="detail"),
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()
urlpatterns = [
    path("", views.home),
    path("admin/", admin.site.urls),
    path("movies/", include("movies.urls")),
    path("api/", include(movie_resource.urls)),
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = "movies"
        excludes = ["date_created"]

movies/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from urllib import request
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Movie


# Create your views here.
def index(request):
    movies = Movie.objects.all()
    template = "movies/index.html"
    return render(request, template, {"movies": movies})


def detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    template = "movies/detail.html"
    return render(request, template, {"movie": movie})

vidly/views.py
from django.shortcuts import render


def home(request):
    return render(request, "home.html")

movies/templates/movies/detail.html
{% extends "base.html" %} {% block content %}
<dl>
  <dt>Title</dt>
  <dd>{{movie.title}}</dd>
  <dt>Genre</dt>
  <dd>{{movie.genre}}</dd>
  <dt>Stock</dt>
  <dd>{{movie.number_in_stock}}</dd>
</dl>
{% endblock %}

movies/templates/movies/index.html
{% extends "base.html" %} {% block content %}
<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Stock</th>
      <th>Daily Rate</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies %}
    <tr>
      <td>
        <a href="{% url "movies:detail" movie.id %}"> {{ movie.title }} </a>
      </td>
      <td>{{ movie.genre }}</td>
      <td>{{ movie.number_in_stock }}</td>
      <td>{{ movie.daily_rate }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Vidly</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Vidly</a>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
  <a href="{% url "movies:index" %}">Movies</a>
{% endblock  %}